export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const BACKGROUND_AJAX = 'BACKGROUND_AJAX';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
export const LOAD_STORIES_SUCCESS = 'LOAD_STORIES_SUCCESS';
export const LOAD_STORIES = 'LOAD_STORIES';
export const TOGGLE_COMMENT = 'TOGGLE_COMMENT';
export const LOADED_LIST = 'LOADED_LIST';
export const INCREMENT_LIST_AMOUNT = 'INCREMENT_LIST_AMOUNT';