export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
export const LOAD_STORIES_SUCCESS = 'LOAD_STORIES_SUCCESS';
export const LOAD_STORIES = 'LOAD_STORIES';
export const TOGGLE_COMMENT = 'TOGGLE_COMMENT';
export const LOAD_LIST_SUCCESS = 'LOAD_LIST_SUCCESS';
export const INCREMENT_LIST_AMOUNT = 'INCREMENT_LIST_AMOUNT';